name: Model Training Pipeline CI

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - '.github/workflows/train.yml'
      - 'training/**'
      - 'config/**'
  pull_request:
    branches:
      - main
    paths:
      - 'main.py'
      - '.github/workflows/train.yml'
      - 'training/**'
      - 'config/**'

env:
  DAGSHUB_REPO_OWNER: ${{ secrets.DAGSHUB_REPO_OWNER }}
  DAGSHUB_REPO_NAME: ${{ secrets.DAGSHUB_REPO_NAME }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
  
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_REPO_OWNER }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_USER_TOKEN }}

jobs:
  check-code-quality:
    name: Lint, Format, and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install package manager
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install python dependencies
        run: uv sync --all-extras --dev

      - name: Check code formatting with Black
        run: uv run black --check main.py training/

      - name: Lint with Flake8
        run: uv run flake8 main.py training/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
      - name: Type check with MyPy
        run: uv run mypy main.py training/

  train-model:
    name: Run MLflow Training
    needs: check-code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install package manager
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install python dependencies
        run: uv sync --all-extras --dev

      - name: Check Env
        run: |
          echo "MLflow Tracking URI is set"
          echo "Dagshub Repo Owner: $DAGSHUB_REPO_OWNER"
          echo "Dagshub Repo Name: $DAGSHUB_REPO_NAME"

      - name: Run mlflow project
        run: |
          uv run mlflow run . -e baseline --env-manager=local
          uv run mlflow run . -e tuning --env-manager=local